using System.Collections.Generic;

namespace C_toolsPlugin;

/// <summary>
/// Short descriptions for common AutoCAD native commands.
/// </summary>
internal static class AcadNativeCommandDescriptions
{
    private static readonly Dictionary<string, string> Map = new(StringComparer.OrdinalIgnoreCase)
    {
        // 绘图
        ["LINE"] = "直线",
        ["ARC"] = "圆弧",
        ["CIRCLE"] = "圆",
        ["POLYGON"] = "正多边形",
        ["RECTANG"] = "矩形",
        ["ELLIPSE"] = "椭圆",
        ["SPLINE"] = "样条曲线",
        ["POINT"] = "点",
        ["XLINE"] = "构造线（无限长）",
        ["RAY"] = "射线",
        ["MLINE"] = "多线",
        ["PLINE"] = "多段线",
        ["POLYLINE"] = "多段线",
        ["HELIX"] = "螺旋",
        ["3DPOLY"] = "三维多段线",
        ["SKETCH"] = "徒手草绘",
        // 修改
        ["ERASE"] = "删除",
        ["COPY"] = "复制",
        ["MOVE"] = "移动",
        ["3DMOVE"] = "三维移动",
        ["ROTATE"] = "旋转",
        ["3DROTATE"] = "三维旋转",
        ["SCALE"] = "缩放",
        ["MIRROR"] = "镜像",
        ["OFFSET"] = "偏移",
        ["ARRAY"] = "阵列",
        ["ARRAYEDIT"] = "编辑关联阵列",
        ["ARRAYRECT"] = "矩形阵列",
        ["ARRAYPOLAR"] = "环形阵列",
        ["ARRAYPATH"] = "路径阵列",
        ["TRIM"] = "修剪",
        ["EXTEND"] = "延伸",
        ["BREAK"] = "打断",
        ["JOIN"] = "合并",
        ["CHAMFER"] = "倒角",
        ["FILLET"] = "圆角",
        ["STRETCH"] = "拉伸",
        ["LENGTHEN"] = "拉长",
        ["ALIGN"] = "对齐",
        ["COPYTOLAYER"] = "复制到其他图层",
        ["EXPLODE"] = "分解",
        ["CHAMFEREDGE"] = "三维边倒角",
        ["CONVTOMESH"] = "转为网格",
        ["CONVTOSOLID"] = "转为实体",
        ["CONVTOSURFACE"] = "转为曲面",
        ["HATCHEDIT"] = "编辑填充/渐变",
        ["MESHSMOOTH"] = "平滑网格",
        ["REVCLOUD"] = "修订云线",
        ["SOLIDEDIT"] = "实体编辑",
        // 夹点编辑类
        ["PEDIT"] = "编辑多段线",
        ["SPLINEDIT"] = "编辑样条曲线",
        ["MLEDIT"] = "编辑多线交点",
        // 块与参照
        ["BLOCK"] = "创建块",
        ["BMAKE"] = "创建块",
        ["INSERT"] = "插入块",
        ["WBLOCK"] = "写块",
        ["BASE"] = "基点",
        ["ATTDEF"] = "定义属性",
        ["ATTEDIT"] = "编辑属性",
        ["ATTEXT"] = "提取属性数据到文件",
        ["BATTMAN"] = "块属性管理器",
        ["BPARAMETER"] = "添加动态块参数",
        ["BSAVEAS"] = "块另存为",
        ["BVSTATE"] = "动态块可见性状态",
        ["BWBLOCKAS"] = "块另存为外部 DWG",
        ["REFEDIT"] = "在位编辑参照",
        ["REFCLOSE"] = "结束参照编辑",
        ["XREF"] = "外部参照",
        ["CLASSICXREF"] = "旧版外部参照管理器",
        ["CLIP"] = "剪裁外部参照/块",
        // 图案与填充
        ["HATCH"] = "图案填充与渐变色",
        ["BHATCH"] = "图案填充",
        ["GRADIENT"] = "渐变填充",
        ["BOUNDARY"] = "边界",
        ["BPOLY"] = "边界多段线",
        ["REGION"] = "面域",
        // 文字与标注
        ["TEXT"] = "单行文字",
        ["DDEDIT"] = "编辑文字/标注文字",
        ["DTEXT"] = "单行文字",
        ["MTEXT"] = "多行文字",
        ["STYLE"] = "文字样式",
        ["DIM"] = "智能标注",
        ["DIM1"] = "旧版标注模式",
        ["DIMEDIT"] = "编辑标注文字/倾斜",
        ["DIMSTYLE"] = "标注样式",
        ["DIMLINEAR"] = "线性标注",
        ["DIMALIGNED"] = "对齐标注",
        ["DIMANGULAR"] = "角度标注",
        ["DIMARC"] = "弧长标注",
        ["DIMRADIUS"] = "半径标注",
        ["DIMDIAMETER"] = "直径标注",
        ["DIMCONTINUE"] = "连续标注",
        ["DIMBASELINE"] = "基线标注",
        ["LEADER"] = "引线",
        ["MLEADER"] = "多重引线",
        ["QDIM"] = "快速标注",
        ["TOLERANCE"] = "形位公差",
        // 图层与特性
        ["LAYER"] = "图层特性管理器",
        ["LAYERP"] = "上一个图层状态",
        ["LAYON"] = "打开图层",
        ["LAYOFF"] = "关闭图层",
        ["LAYFRZ"] = "冻结图层",
        ["LAYTHW"] = "解冻所有图层",
        ["LAYISO"] = "图层隔离",
        ["LAYLCK"] = "锁定图层",
        ["LAYULK"] = "解锁图层",
        ["LAYMCH"] = "图层匹配",
        ["LAYUNISO"] = "取消图层隔离",
        ["LAYMCUR"] = "将对象图层设为当前层",
        ["MATCHPROP"] = "特性匹配",
        ["PROPERTIES"] = "特性面板",
        ["CHPROP"] = "修改对象特性",
        ["DRAWORDER"] = "调整对象绘图次序",
        ["COLOR"] = "设置颜色",
        ["LINETYPE"] = "线型管理器",
        ["LTSCALE"] = "线型比例",
        ["LWEIGHT"] = "线宽",
        // 视图与导航
        ["ZOOM"] = "缩放视图",
        ["PAN"] = "平移",
        ["LAYOUT"] = "布局",
        ["VIEW"] = "命名视图",
        ["VIEWBASE"] = "从模型创建基视图",
        ["VIEWPORTS"] = "视口配置",
        ["VPORTS"] = "视口",
        ["VPLAYER"] = "按视口控制图层",
        ["VPOINT"] = "设置三维观察方向",
        ["MVIEW"] = "布局视口",
        ["REGEN"] = "重生成",
        ["REGENALL"] = "全部重生成",
        ["REDRAW"] = "重画",
        ["3DORBIT"] = "动态观察（三维）",
        ["HIDE"] = "隐藏背面线",
        ["PLAN"] = "平面视图",
        ["RENDER"] = "渲染",
        ["SHADE"] = "着色显示",
        ["SHADEMODE"] = "着色模式",
        // 查询与实用工具
        ["3DCONFIG"] = "图形性能设置",
        ["3DOSNAP"] = "三维对象捕捉设置",
        ["ABOUT"] = "关于产品",
        ["ARX"] = "管理 ObjectARX 应用",
        ["DIST"] = "距离",
        ["AREA"] = "面积/周长",
        ["ID"] = "点坐标",
        ["LIST"] = "列表显示对象数据",
        ["MASSPROP"] = "质量/面域特性",
        ["MEASUREGEOM"] = "快速测量",
        ["QUICKCALC"] = "快速计算器",
        ["QSELECT"] = "快速选择",
        ["FILTER"] = "对象选择过滤器",
        ["CAL"] = "计算器",
        ["GEOMARKLATLONG"] = "按经纬度放置位置标记",
        ["GEOMARKME"] = "按当前位置放置位置标记",
        ["GEOMARKPOINT"] = "按指定点放置位置标记",
        ["GEOMARKPOSITION"] = "放置地理位置标记",
        // 文件与打印
        ["ARCHIVE"] = "归档文件",
        ["DWGCONVERT"] = "批量转换 DWG 版本",
        ["DXFIN"] = "导入 DXF",
        ["DXFOUT"] = "导出 DXF",
        ["NEW"] = "新建图形",
        ["OPEN"] = "打开图形",
        ["QSAVE"] = "快速保存",
        ["SAVE"] = "保存",
        ["SAVEAS"] = "另存为",
        ["CLOSE"] = "关闭",
        ["QUIT"] = "退出",
        ["ETRANSMIT"] = "打包图纸及依赖文件",
        ["OPENDWFMARKUP"] = "打开 DWF 批注集",
        ["PLOT"] = "打印",
        ["PLOTSTAMP"] = "打印戳记",
        ["PLOTSTYLE"] = "打印样式",
        ["PSETUPIN"] = "导入页面设置",
        ["PSOUT"] = "导出 PostScript 文件",
        ["PRINT"] = "打印",
        ["PREVIEW"] = "打印预览",
        ["PUBLISH"] = "发布",
        // 清理与核查
        ["PURGE"] = "清理未使用项",
        ["AUDIT"] = "核查图形",
        ["RECOVER"] = "修复打开图形",
        // 组与选择
        ["GROUP"] = "组",
        ["SELECT"] = "选择对象",
        ["UNDO"] = "撤销",
        ["U"] = "撤销一步",
        ["REDO"] = "重做",
        ["OOPS"] = "恢复刚删除对象",
        // 捕捉与辅助
        ["OSNAP"] = "对象捕捉设置",
        ["DSETTINGS"] = "草图设置（捕捉/栅格/极轴等）",
        ["ORTHO"] = "正交模式开关",
        ["GRID"] = "栅格显示开关",
        ["SNAP"] = "捕捉开关",
        ["POLAR"] = "极轴追踪",
        ["QPMODE"] = "快捷特性",
        // UCS / 三维常用
        ["UCS"] = "用户坐标系",
        ["PLANESURF"] = "平面曲面",
        ["EXTRUDE"] = "拉伸（三维）",
        ["REVOLVE"] = "旋转（三维）",
        ["SWEEP"] = "扫掠",
        ["LOFT"] = "放样",
        ["PRESSPULL"] = "按住并拖动",
        ["SLICE"] = "剖切",
        ["SECTIONPLANE"] = "截面平面",
        ["BOX"] = "长方体",
        ["SPHERE"] = "球体",
        ["CYLINDER"] = "圆柱体",
        ["CONE"] = "圆锥体",
        ["PYRAMID"] = "棱锥体",
        ["WEDGE"] = "楔体",
        ["TORUS"] = "圆环体",
        ["UNION"] = "并集",
        ["SUBTRACT"] = "差集",
        ["INTERSECT"] = "交集",
        // 设计中心与工具选项板
        ["ADCENTER"] = "设计中心",
        ["CLASSICIMAGE"] = "旧版图像管理器",
        ["CUILOAD"] = "加载自定义界面文件",
        ["CUIUNLOAD"] = "卸载自定义界面文件",
        ["EXECUTETOOL"] = "执行工具选项板工具",
        ["IMAGE"] = "管理图像参照",
        ["IMAGEADJUST"] = "调整图像亮度/对比度/淡化",
        ["MENULOAD"] = "加载菜单文件",
        ["MENUUNLOAD"] = "卸载菜单文件",
        ["TOOLBAR"] = "显示/隐藏工具栏",
        ["TOOLPALETTES"] = "工具选项板",
        ["WSSAVE"] = "保存工作空间",
        // 表格与字段
        ["EDITTABLECELL"] = "编辑表格单元格",
        ["TABLE"] = "表格",
        ["TABLEDIT"] = "编辑表格内容",
        ["TABLESTYLE"] = "表格样式",
        ["FIELD"] = "字段",
        // 其他常用
        ["CONVERT"] = "转换旧版填充/多段线",
        ["CONVERTCTB"] = "CTB 转 STB",
        ["CONVERTPSTYLES"] = "转换打印样式模式",
        ["MATCHCELL"] = "匹配单元格",
        ["BCLOSE"] = "关闭块编辑器",
        ["BEDIT"] = "块编辑器",
        ["LAYDEL"] = "删除图层",
        ["LAYMRG"] = "合并图层",
        ["LAYWALK"] = "图层漫游",
        ["LAYVPI"] = "视口图层冻结",
        ["COPYBASE"] = "带基点复制",
        ["PASTECLIP"] = "粘贴",
        ["PASTEBLOCK"] = "粘贴为块",
        ["PASTEORIG"] = "原坐标粘贴",
        ["QNEW"] = "快速新建",
        ["RENAME"] = "重命名（块/图层等）",
        ["SCALELISTEDIT"] = "编辑比例列表",
        ["SETVAR"] = "设置系统变量",
        ["SYSWINDOWS"] = "窗口排列",
        ["TEXTTOFRONT"] = "文字与标注前置",
        ["UNITS"] = "图形单位",
        ["VBALOAD"] = "加载 VBA 项目",
        ["VBAIDE"] = "VBA 编辑器",
        ["VBARUN"] = "运行 VBA 宏",
        ["XBIND"] = "绑定外部参照依赖",
        ["XCLIP"] = "剪裁外部参照",
        ["XLIST"] = "外部参照/块列表",
    };

    internal static IEnumerable<string> CommandNames => Map.Keys;

    internal static bool Contains(string commandName)
    {
        if (string.IsNullOrWhiteSpace(commandName))
            return false;
        return Map.ContainsKey(commandName.Trim());
    }

    internal static bool TryGet(string commandName, out string description)
    {
        description = "";
        if (string.IsNullOrWhiteSpace(commandName))
            return false;

        var key = commandName.Trim();
        if (Map.TryGetValue(key, out description!))
            return true;
        // 命令行形式 -LAYER、-BLOCK 等与 LAYER、BLOCK 共用说明
        if (key.StartsWith("-", StringComparison.Ordinal) && Map.TryGetValue(key.TrimStart('-'), out description!))
            return true;
        return false;
    }
}
